/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_izforge_izpack_util_os_WinSetupAPIBase */

#ifndef _Included_com_izforge_izpack_util_os_WinSetupAPIBase
#define _Included_com_izforge_izpack_util_os_WinSetupAPIBase
#ifdef __cplusplus
extern "C" {
#endif
#undef com_izforge_izpack_util_os_WinSetupAPIBase_INVALID_HANDLE_VALUE
#define com_izforge_izpack_util_os_WinSetupAPIBase_INVALID_HANDLE_VALUE -1L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_DELETESOURCE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_DELETESOURCE 1L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_REPLACEONLY
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_REPLACEONLY 2L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NEWER
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NEWER 4L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NEWER_OR_SAME
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NEWER_OR_SAME 4L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOOVERWRITE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOOVERWRITE 8L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NODECOMP
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NODECOMP 16L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_LANGUAGEAWARE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_LANGUAGEAWARE 32L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_SOURCE_ABSOLUTE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_SOURCE_ABSOLUTE 64L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_SOURCEPATH_ABSOLUTE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_SOURCEPATH_ABSOLUTE 128L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_IN_USE_NEEDS_REBOOT
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_IN_USE_NEEDS_REBOOT 256L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_FORCE_IN_USE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_FORCE_IN_USE 512L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOSKIP
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOSKIP 1024L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_FLAG_CABINETCONTINUATION
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_FLAG_CABINETCONTINUATION 2048L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_FORCE_NOOVERWRITE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_FORCE_NOOVERWRITE 4096L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_FORCE_NEWER
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_FORCE_NEWER 8192L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_WARNIFSKIP
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_WARNIFSKIP 16384L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOBROWSE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOBROWSE 32768L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NEWER_ONLY
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NEWER_ONLY 65536L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_SOURCE_SIS_MASTER
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_SOURCE_SIS_MASTER 131072L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_OEMINF_CATALOG_ONLY
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_OEMINF_CATALOG_ONLY 262144L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_REPLACE_BOOT_FILE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_REPLACE_BOOT_FILE 524288L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOPRUNE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SP_COPY_NOPRUNE 1048576L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SPFILEQ_FILE_IN_USE
#define com_izforge_izpack_util_os_WinSetupAPIBase_SPFILEQ_FILE_IN_USE 1L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SPFILEQ_REBOOT_RECOMMENDED
#define com_izforge_izpack_util_os_WinSetupAPIBase_SPFILEQ_REBOOT_RECOMMENDED 2L
#undef com_izforge_izpack_util_os_WinSetupAPIBase_SPFILEQ_REBOOT_IN_PROGRESS
#define com_izforge_izpack_util_os_WinSetupAPIBase_SPFILEQ_REBOOT_IN_PROGRESS 4L
/*
 * Class:     com_izforge_izpack_util_os_WinSetupAPIBase
 * Method:    SetupOpenFileQueue
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_izforge_izpack_util_os_WinSetupAPIBase_SetupOpenFileQueue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_izforge_izpack_util_os_WinSetupAPIBase
 * Method:    SetupCloseFileQueue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_izforge_izpack_util_os_WinSetupAPIBase_SetupCloseFileQueue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_izforge_izpack_util_os_WinSetupAPIBase
 * Method:    SetupQueueCopy
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_izforge_izpack_util_os_WinSetupAPIBase_SetupQueueCopy
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_izforge_izpack_util_os_WinSetupAPIBase
 * Method:    SetupQueueDelete
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_izforge_izpack_util_os_WinSetupAPIBase_SetupQueueDelete
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_izforge_izpack_util_os_WinSetupAPIBase
 * Method:    SetupQueueRename
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_izforge_izpack_util_os_WinSetupAPIBase_SetupQueueRename
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     com_izforge_izpack_util_os_WinSetupAPIBase
 * Method:    SetupCommitFileQueue
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_izforge_izpack_util_os_WinSetupAPIBase_SetupCommitFileQueue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_izforge_izpack_util_os_WinSetupAPIBase
 * Method:    SetupPromptReboot
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_izforge_izpack_util_os_WinSetupAPIBase_SetupPromptReboot
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
